export const ERROR_CODES = {
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_REQUIRED: 'CONFIG_REQUIRED',
  GIT_FAILED: 'GIT_FAILED',
  EMPTY_DIFF: 'EMPTY_DIFF',
  DIFF_TOO_LARGE: 'DIFF_TOO_LARGE',
  OLLAMA_UNAVAILABLE: 'OLLAMA_UNAVAILABLE',
  MODEL_RESPONSE_INVALID: 'MODEL_RESPONSE_INVALID',
  OUTPUT_FAILED: 'OUTPUT_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
